

type TeamMember = {
  link: string,
  nickname: string,
  fontNickname: [string,string],
  fullname: string,
  Divisi: string,
  fontDivisi: [string,string],
  image: string,
  image2:string
}


type Team = {
  Team: string,
  member: TeamMember[]
}

type Teams = Team[]


const ourTeam: Teams = [
  {
    Team: "Core Team",
    member: [
      {
        link: "/fams/tirta-rendy-siahaan",
        nickname: "TIRTA",
        fontNickname: ["45px", "30px"],
        fullname: "Tirta Rendy S",
        Divisi: "CORE",
        fontDivisi: ["50px", "35px"],
        image: "/team/tirta-rendy-siahaan1.png",
        image2: "/team/tirta-rendy-siahaan2.png",
      },
      {
        link: "/fams/muhammad-hamiz-ghani-ayusha",
        nickname: "GHANI",
        fontNickname: ["45px", "30px"],
        fullname: "Hamiz Ghani",
        Divisi: "CORE",
        fontDivisi: ["50px", "35px"],
        image: "/team/muhammad-hamiz-ghani-ayusha1.png",
        image2: "/team/muhammad-hamiz-ghani-ayusha2.png",
      },
      {
        link: "/fams/geraldus-catur-gigih-wahyudi",
        nickname: "GIGIH",
        fontNickname: ["45px", "30px"],
        fullname: "Geraldus Catur Gigih",
        Divisi: "CORE",
        fontDivisi: ["50px", "35px"],
        image: "/team/geraldus-catur-gigih-wahyudi1.png",
        image2: "/team/geraldus-catur-gigih-wahyudi2.png",
      },
    ],
  },
  {
    Team: "IT Developer",
    member: [
      {
        link: "/fams/muhammad-fauzan",
        nickname: "FAUZAN",
        fontNickname: ["38px", "27px"],
        fullname: "Muhammad Fauzan",
        Divisi: "IT DEV",
        fontDivisi: ["45px", "27px"],
        image: "/team/muhammad-fauzan1.png",
        image2: "/team/muhammad-fauzan2.png",
      },
      {
        link: "/fams/gerry-bima-putra",
        nickname: "GERRY",
        fontNickname: ["45px", "30px"],
        fullname: "Gerry Bima Putra",
        Divisi: "IT DEV",
        fontDivisi: ["45px", "27px"],
        image: "/team/gerry-bima-putra1.png",
        image2: "/team/gerry-bima-putra2.png",
      },
      {
        link: "/fams/muhamad-hakim-nizami",
        nickname: "HAKIM",
        fontNickname: ["42px", "28px"],
        fullname: "Hakim Nizami",
        Divisi: "IT DEV",
        fontDivisi: ["45px", "27px"],
        image: "/team/muhamad-hakim-nizami1.png",
        image2: "/team/muhamad-hakim-nizami2.png",
      },
      {
        link: "/fams/kevin-cornellius-widjaja",
        nickname: "KEVIN",
        fontNickname: ["45px", "30px"],
        fullname: "Kevin Cornellius",
        Divisi: "IT DEV",
        fontDivisi: ["45px", "27px"],
        image: "/team/kevin-cornellius-widjaja1.png",
        image2: "/team/kevin-cornellius-widjaja2.png",
      },
      {
        link: "/fams/radhya-cahya-kusuma",
        nickname: "RADHYA",
        fontNickname: ["35px", "25px"],
        fullname: "Radhya Cahya",
        Divisi: "IT DEV",
        fontDivisi: ["45px", "27px"],
        image: "/team/radhya-cahya-kusuma1.png",
        image2: "/team/radhya-cahya-kusuma2.png",
      },
      {
        link: "/fams/vincent-valentino-oei",
        nickname: "VINCENT",
        fontNickname: ["33px", "22px"],
        fullname: "Vincent Valentino",
        Divisi: "IT DEV",
        fontDivisi: ["45px", "27px"],
        image: "/team/vincent-valentino-oei1.png",
        image2: "/team/vincent-valentino-oei2.png",
      },
    ],
  },
  {
    Team: "UI/UX Designer",
    member: [
      {
        link: "/fams/kadek-chandra-rasmi",
        nickname: "CHANDRA",
        fontNickname: ["30px", "20px"],
        fullname: "Kadek Chandra",
        Divisi: "UI/UX",
        fontDivisi: ["45px", "27px"],
        image: "/team/kadek-chandra-rasmi1.png",
        image2: "/team/kadek-chandra-rasmi2.png",
      },
      {
        link: "/fams/nadin-ananda",
        nickname: "NADIN",
        fontNickname: ["45px", "32px"],
        fullname: "Nadin Ananda",
        Divisi: "UI/UX",
        fontDivisi: ["45px", "27px"],
        image: "/team/nadin-ananda1.png",
        image2: "/team/nadin-ananda2.png",
      },
      {
        link: "/fams/syifa-anabella",
        nickname: "SYIFA",
        fontNickname: ["45px", "32px"],
        fullname: "Syifa Anabella",
        Divisi: "UI/UX",
        fontDivisi: ["45px", "27px"],
        image: "/team/syifa-anabella1.png",
        image2: "/team/syifa-anabella2.png",
      },
      {
        link: "/fams/inayah-saffanah-asri",
        nickname: "INAYAH",
        fontNickname: ["36px", "25px"],
        fullname: "Inayah Saffanah",
        Divisi: "UI/UX",
        fontDivisi: ["45px", "27px"],
        image: "/team/inayah-saffanah-asri1.png",
        image2: "/team/inayah-saffanah-asri2.png",
      },
      {
        link: "/fams/shelia-vellicita",
        nickname: "SHELIA",
        fontNickname: ["33px", "22px"],
        fullname: "Shelia Vellicita",
        Divisi: "UI/UX",
        fontDivisi: ["45px", "27px"],
        image: "/team/shelia-vellicita1.png",
        image2: "/team/shelia-vellicita2.png",
      },
    ],
  },
  {
    Team: "Akademik",
    member: [
      {
        link: "/fams/aldebaran-rahman-adhitya",
        nickname: "ALDEBARAN",
        fontNickname: ["24px", "18px"],
        fullname: "Aldebaran Rahman",
        Divisi: "Akademik",
        fontDivisi: ["30px", "20px"],
        image: "/team/aldebaran-rahman-adhitya1.png",
        image2: "/team/aldebaran-rahman-adhitya2.png",
      },
      {
        link: "/fams/go-nadine-audelia",
        nickname: "NADINE",
        fontNickname: ["38px", "27px"],
        fullname: "Go Nadine Audelia",
        Divisi: "Akademik",
        fontDivisi: ["30px", "20px"],
        image: "/team/go-nadine-audelia1.png",
        image2: "/team/go-nadine-audelia2.png",
      },
      {
        link: "/fams/riyaan-baihaqi",
        nickname: "RIYAAN",
        fontNickname: ["38px", "27px"],
        fullname: "Riyaan Baihaqi",
        Divisi: "Akademik",
        fontDivisi: ["30px", "20px"],
        image: "/team/riyaan-baihaqi1.png",
        image2: "/team/riyaan-baihaqi2.png",
      },
      {
        link: "/fams/naomi-shakila-isbono",
        nickname: "NAOMI",
        fontNickname: ["42px", "28px"],
        fullname: "Naomi Isbono",
        Divisi: "Akademik",
        fontDivisi: ["30px", "20px"],
        image: "/team/naomi-shakila-isbono1.png",
        image2: "/team/naomi-shakila-isbono2.png",
      },
      {
        link: "/fams/syakirah-zahra-dhawini",
        nickname: "SYAKIRAH",
        fontNickname: ["26px", "20px"],
        fullname: "Syakirah Zahra Dhawini",
        Divisi: "Akademik",
        fontDivisi: ["30px", "20px"],
        image: "/team/syakirah-zahra-dhawini1.png",
        image2: "/team/syakirah-zahra-dhawini2.png",
      },
      {
        link: "/fams/sean-marcello-maheron",
        nickname: "SEAN",
        fontNickname: ["50px", "36px"],
        fullname: "Sean Marcello",
        Divisi: "Akademik",
        fontDivisi: ["30px", "20px"],
        image: "/team/sean-marcello-maheron1.png",
        image2: "/team/sean-marcello-maheron2.png",
      },
      {
        link: "/fams/maira-azma-shaliha",
        nickname: "MAIRA",
        fontNickname: ["42px", "28px"],
        fullname: "Maira Azma",
        Divisi: "Akademik",
        fontDivisi: ["30px", "20px"],
        image: "/team/maira-azma-shaliha1.png",
        image2: "/team/maira-azma-shaliha2.png",
      },
    ],
  },
  {
    Team: "Creative",
    member: [
      {
        link: "/fams/annisa-fakhira-cendekia",
        nickname: "ANNISA",
        fontNickname: ["32px", "28px"],
        fullname: "Annisa Fakhira",
        Divisi: "Creative",
        fontDivisi: ["30px", "20px"],
        image: "/team/annisa-fakhira-cendekia1.png",
        image2: "/team/annisa-fakhira-cendekia2.png",
      },
      {
        link: "/fams/khansa-dinda-arya-putri",
        nickname: "KHANSA",
        fontNickname: ["32px", "28px"],
        fullname: "Khansa Dinda",
        Divisi: "Creative",
        fontDivisi: ["30px", "20px"],
        image: "/team/khansa-dinda-arya-putri1.png",
        image2: "/team/khansa-dinda-arya-putri2.png",
      },
      {
        link: "/fams/muhammad-azzam-fathurrahman",
        nickname: "AZZAM",
        fontNickname: ["32px", "28px"],
        fullname: "Muhammad Azzam",
        Divisi: "Creative",
        fontDivisi: ["30px", "20px"],
        image: "/team/muhammad-azzam-fathurrahman1.png",
        image2: "/team/muhammad-azzam-fathurrahman2.png",
      },
      {
        link: "/fams/muhammad-rafi-sugianto",
        nickname: "RAFI",
        fontNickname: ["50px", "35px"],
        fullname: "Muhammad Rafi Sugianto",
        Divisi: "Creative",
        fontDivisi: ["30px", "20px"],
        image: "/team/muhammad-rafi-sugianto1.png",
        image2: "/team/muhammad-rafi-sugianto2.png",
      },
      {
        link: "/fams/raden-pandji-mohammad-dimaz-bagus-hayyii-dausti-surya",
        nickname: "DIMAZ",
        fontNickname: ["35px", "31px"],
        fullname: "RPM Dimaz",
        Divisi: "Creative",
        fontDivisi: ["30px", "20px"],
        image: "/team/raden-pandji-mohammad-dimaz-bagus-hayyii-dausti-surya1.png",
        image2: "/team/raden-pandji-mohammad-dimaz-bagus-hayyii-dausti-surya2.png",
      },
      
    ],
  },
  {
    Team: "Gathering",
    member: [
      {
        link: "/fams/daffa-ismail",
        nickname: "DAFFA",
        fontNickname: ["36px", "32px"],
        fullname: "Daffa Ismail",
        Divisi: "Gathering",
        fontDivisi: ["26px", "16px"],
        image: "/team/daffa-ismail1.png",
        image2: "/team/daffa-ismail2.png",
      },
      {
        link: "/fams/raihana-auni-zakia",
        nickname: "RAIHANA",
        fontNickname: ["26px", "20px"],
        fullname: "Raihana Auni",
        Divisi: "Gathering",
        fontDivisi: ["26px", "16px"],
        image: "/team/raihana-auni-zakia1.png",
        image2: "/team/raihana-auni-zakia2.png",
      },
      {
        link: "/fams/nita-pasaribu",
        nickname: "NITA",
        fontNickname: ["50px", "35px"],
        fullname: "Nita Pasaribu",
        Divisi: "Gathering",
        fontDivisi: ["26px", "16px"],
        image: "/team/nita-pasaribu1.png",
        image2: "/team/nita-pasaribu2.png",
      },
      {
        link: "/fams/vidya-pramudita-andini",
        nickname: "VIDYA",
        fontNickname: ["36px", "32px"],
        fullname: "Vidya Pramudita",
        Divisi: "Gathering",
        fontDivisi: ["26px", "16px"],
        image: "/team/vidya-pramudita-andini1.png",
        image2: "/team/vidya-pramudita-andini2.png",
      },
    ],
  },
  {
    Team: "Laskar Biru Merah",
    member: [
      {
        link: "/fams/muhammad-hafizh",
        nickname: "HAFIZH",
        fontNickname: ["34px", "24px"],
        fullname: "Muhammad Hafizh",
        Divisi: "LBM",
        fontDivisi: ["40px", "25px"],
        image: "/team/muhammad-hafizh1.png",
        image2: "/team/muhammad-hafizh2.png"
      },
      {
        link: "/fams/muhammad-salman-fahri",
        nickname: "SALMAN",
        fontNickname: ["34px", "24px"],
        fullname: "M Salman Fahri",
        Divisi: "LBM",
        fontDivisi: ["40px", "25px"],
        image: "/team/muhammad-salman-fahri1.png",
        image2: "/team/muhammad-salman-fahri2.png"
      },
      {
        link: "/fams/jonathan-immanuel-tampubolon",
        nickname: "JONATHAN",
        fontNickname: ["26px", "18px"],
        fullname: "Jonathan Immanuel",
        Divisi: "LBM",
        fontDivisi: ["40px", "25px"],
        image: "/team/jonathan-immanuel-tampubolon1.png",
        image2: "/team/jonathan-immanuel-tampubolon2.png"
      },
      {
        link: "/fams/amadio-juno-trisanto",
        nickname: "AMADIO",
        fontNickname: ["34px", "24px"],
        fullname: "Amadio Juno",
        Divisi: "LBM",
        fontDivisi: ["40px", "25px"],
        image: "/team/amadio-juno-trisanto1.png",
        image2: "/team/amadio-juno-trisanto2.png"
      },
      {
        link: "/fams/antonius-daniel-maruli-nainggolan",
        nickname: "DANIEL",
        fontNickname: ["34px", "24px"],
        fullname: "Antonius Daniel",
        Divisi: "LBM",
        fontDivisi: ["40px", "25px"],
        image: "/team/antonius-daniel-maruli-nainggolan1.png",
        image2: "/team/antonius-daniel-maruli-nainggolan2.png"
      },
      {
        link: "/fams/fairuz-akhtar-randrasyah",
        nickname: "RANDRA",
        fontNickname: ["34px", "24px"],
        fullname: "Akhtar Randrasyah",
        Divisi: "LBM",
        fontDivisi: ["40px", "25px"],
        image: "/team/fairuz-akhtar-randrasyah1.png",
        image2: "/team/fairuz-akhtar-randrasyah2.png"
      },
      {
        link: "/fams/pria-abhirama-dewa",
        nickname: "ABHIRAMA",
        fontNickname: ["24px", "18px"],
        fullname: "Pria Abhirama Dewa",
        Divisi: "LBM",
        fontDivisi: ["40px", "25px"],
        image: "/team/pria-abhirama-dewa1.png",
        image2: "/team/pria-abhirama-dewa2.png"
      },
      {
        link: "/fams/rayhan-derya-maheswara",
        nickname: "RAYHAN",
        fontNickname: ["34px", "24px"],
        fullname: "Rayhan Derya",
        Divisi: "LBM",
        fontDivisi: ["40px", "25px"],
        image: "/team/rayhan-derya-maheswara1.png",
        image2: "/team/rayhan-derya-maheswara2.png"
      },
      {
        link: "/fams/raqilla-al-abrar",
        nickname: "RAQILLA",
        fontNickname: ["34px", "24px"],
        fullname: "Raqilla Al-Abrar",
        Divisi: "LBM",
        fontDivisi: ["40px", "25px"],
        image: "/team/raqilla-al-abrar1.png",
        image2: "/team/raqilla-al-abrar2.png"
      },
      {
        link: "/fams/febrian-abimanyu-wijanarko",
        nickname: "FEBRIAN",
        fontNickname: ["34px", "24px"],
        fullname: "Febrian Abimanyu Wijanarko",
        Divisi: "LBM",
        fontDivisi: ["40px", "25px"],
        image: "/team/febrian-abimanyu-wijanarko1.png",
        image2: "/team/febrian-abimanyu-wijanarko2.png"
      },
      {
        link: "/fams/muhammad-khayru-rafani",
        nickname: "KHAYRU",
        fontNickname: ["34px", "24px"],
        fullname: "Muhammad Khayru Rafani",
        Divisi: "LBM",
        fontDivisi: ["40px", "25px"],
        image: "/team/muhammad-khayru-rafani1.png",
        image2: "/team/muhammad-khayru-rafani2.png"
      },
      {
        link: "/fams/ainur-fadhil",
        nickname: "FADHIL",
        fontNickname: ["34px", "24px"],
        fullname: "Ainur Fadhil",
        Divisi: "LBM",
        fontDivisi: ["40px", "25px"],
        image: "/team/ainur-fadhil1.png",
        image2: "/team/ainur-fadhil2.png"
      },
      {
        link: "/fams/firos-aqiela-zufa",
        nickname: "AQIELA",
        fontNickname: ["34px", "24px"],
        fullname: "Firos Aqiela Zufa",
        Divisi: "LBM",
        fontDivisi: ["40px", "25px"],
        image: "/team/firos-aqiela-zufa1.png",
        image2: "/team/firos-aqiela-zufa2.png"
      },
      {
        link: "/fams/muhammad-indi-ryan-pratama",
        nickname: "TAMA",
        fontNickname: ["38px", "28px"],
        fullname: "Muhammad Indi Ryan Pratama",
        Divisi: "LBM",
        fontDivisi: ["40px", "25px"],
        image: "/team/muhammad-indi-ryan-pratama1.png",
        image2: "/team/muhammad-indi-ryan-pratama2.png"
      },
      {
        link: "/fams/haikal-muzaki",
        nickname: "HAIKAL",
        fontNickname: ["34px", "24px"],
        fullname: "Haikal Muzaki",
        Divisi: "LBM",
        fontDivisi: ["40px", "25px"],
        image: "/team/haikal-muzaki1.png",
        image2: "/team/haikal-muzaki2.png"
      },
    ]
  }
];

  
  export default ourTeam;
  