

type TeamMember = {
  link: string,
  nickname: string,
  fontNickname: [string,string],
  fullname: string,
  Divisi: string,
  fontDivisi: [string,string],
  image: string,
  image2:string
}


type Team = {
  Team: string,
  member: TeamMember[]
}

type Teams = Team[]


const ourTeam: Teams = [
    {
      Team: "Core Team",
      member: [
        {
          link: "#",
          nickname: "TIRTA",
          fontNickname: ["45px", "30px"],
          fullname: "Tirta Rendy S",
          Divisi: "CORE",
          fontDivisi: ["50px", "35px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "GHANI",
          fontNickname: ["45px", "30px"],
          fullname: "Hamiz Ghani",
          Divisi: "CORE",
          fontDivisi: ["50px", "35px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "GIGIH",
          fontNickname: ["45px", "30px"],
          fullname: "Geraldus Catur Gigih",
          Divisi: "CORE",
          fontDivisi: ["50px", "35px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
      ],
    },
    {
      Team: "IT Developer",
      member: [
        {
          link: "#",
          nickname: "FAUZAN",
          fontNickname: ["38px", "27px"],
          fullname: "Muhammad Fauzan",
          Divisi: "IT DEV",
          fontDivisi: ["45px", "27px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "GERRY",
          fontNickname: ["45px", "30px"],
          fullname: "Gerry Bima Putra",
          Divisi: "IT DEV",
          fontDivisi: ["45px", "27px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "HAKIM",
          fontNickname: ["42px", "28px"],
          fullname: "Hakim Nizami",
          Divisi: "IT DEV",
          fontDivisi: ["45px", "27px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "KEVIN",
          fontNickname: ["45px", "30px"],
          fullname: "Kevin Cornellius",
          Divisi: "IT DEV",
          fontDivisi: ["45px", "27px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "RADHYA",
          fontNickname: ["35px", "25px"],
          fullname: "Radhya Cahya",
          Divisi: "IT DEV",
          fontDivisi: ["45px", "27px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "VINCENT",
          fontNickname: ["33px", "22px"],
          fullname: "Vincent Valentino ",
          Divisi: "IT DEV",
          fontDivisi: ["45px", "27px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
      ],
    },
    {
      Team: "UI/UX Designer",
      member: [
        {
          link: "#",
          nickname: "CHANDRA",
          fontNickname: ["30px", "20px"],
          fullname: "Kadek Chandra",
          Divisi: "UI/UX",
          fontDivisi: ["45px", "27px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "SYIFA",
          fontNickname: ["50px", "35px"],
          fullname: "Syifa Anabella",
          Divisi: "UI/UX",
          fontDivisi: ["45px", "27px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "INAYAH",
          fontNickname: ["40px", "26px"],
          fullname: "Inayah Saffanah",
          Divisi: "UI/UX",
          fontDivisi: ["45px", "27px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "SHELIA",
          fontNickname: ["40px", "25px"],
          fullname: "Shelia Vellicita",
          Divisi: "UI/UX",
          fontDivisi: ["45px", "27px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "NADIN",
          fontNickname: ["45px", "32px"],
          fullname: "Nadin Ananda",
          Divisi: "UI/UX",
          fontDivisi: ["45px", "27px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
      ],
    },
    {
        Team: "Creative",
        member: [
          {
            link: "#",
            nickname: "JULUKAN",
            fontNickname: ["30px", "22px"],
            fullname: "Nama Panjang",
            Divisi: "Creative",
            fontDivisi: ["33px", "22px"],
            image: "/team/tes.png",
            image2: "/team/tes2.png",
          },
          {
            link: "#",
            nickname: "JULUKAN",
            fontNickname: ["30px", "22px"],
            fullname: "Nama Panjang",
            Divisi: "Creative",
            fontDivisi: ["33px", "22px"],
            image: "/team/tes.png",
            image2: "/team/tes2.png",
          },
          {
            link: "#",
            nickname: "JULUKAN",
            fontNickname: ["30px", "22px"],
            fullname: "Nama Panjang",
            Divisi: "Creative",
            fontDivisi: ["33px", "22px"],
            image: "/team/tes.png",
            image2: "/team/tes2.png",
          },
        ],
      },
    {
      Team: "Akademik",
      member: [
        {
          link: "#",
          nickname: "NADINE",
          fontNickname: ["38px", "27px"],
          fullname: "Go Nadine Audelia",
          Divisi: "Akademik",
          fontDivisi: ["30px", "20px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "RIYAAN",
          fontNickname: ["38px", "27px"],
          fullname: "Riyaan Baihaqi",
          Divisi: "Akademik",
          fontDivisi: ["30px", "20px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "NAOMI",
          fontNickname: ["42px", "28px"],
          fullname: "Naomi Isbono",
          Divisi: "Akademik",
          fontDivisi: ["30px", "20px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "SYAKIRAH",
          fontNickname: ["28px", "19px"],
          fullname: "Syakirah Zahra",
          Divisi: "Akademik",
          fontDivisi: ["30px", "20px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "SEAN",
          fontNickname: ["50px", "35px"],
          fullname: "Sean Marcello",
          Divisi: "Akademik",
          fontDivisi: ["30px", "20px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "MAIRA",
          fontNickname: ["40px", "30px"],
          fullname: "Maira Azma Shaliha",
          Divisi: "Akademik",
          fontDivisi: ["30px", "20px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "ALDEBARAN",
          fontNickname: ["22px", "15px"],
          fullname: "Aldebaran Rahman",
          Divisi: "Akademik",
          fontDivisi: ["30px", "20px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
      ],
    },
    {
        Team: "Gathering",
        member: [
          {
            link: "#",
            nickname: "DAFFA",
            fontNickname: ["41px", "30px"],
            fullname: "Daffa Ismail",
            Divisi: "Gathering",
            fontDivisi: ["28px", "20px"],
            image: "/team/tes.png",
            image2: "/team/tes2.png",
          },
          {
            link: "#",
            nickname: "RAIHANA",
            fontNickname: ["30px", "19px"],
            fullname: "Raihana Auni",
            Divisi: "Gathering",
            fontDivisi: ["28px", "20px"],
            image: "/team/tes.png",
            image2: "/team/tes2.png",
          },
          {
            link: "#",
            nickname: "NITA",
            fontNickname: ["50px", "35px"],
            fullname: "Nita Pasaribu",
            Divisi: "Gathering",
            fontDivisi: ["28px", "20px"],
            image: "/team/tes.png",
            image2: "/team/tes2.png",
          },
          {
            link: "#",
            nickname: "VIDYA",
            fontNickname: ["45px", "30px"],
            fullname: "Vidya Pramudita",
            Divisi: "Gathering",
            fontDivisi: ["28px", "20px"],
            image: "/team/tes.png",
            image2: "/team/tes2.png",
          },
        ],
      },
    {
      Team: "Laskar Biru Merah",
      member: [
        {
          link: "#",
          nickname: "HAFIZH",
          fontNickname: ["38px", "27px"],
          fullname: "Muhammad Hafizh",
          Divisi: "LASKAR",
          fontDivisi: ["35px", "25px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "SALMAN",
          fontNickname: ["33px", "23px"],
          fullname: "Muhammad Salman",
          Divisi: "LASKAR",
          fontDivisi: ["35px", "25px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "RANDRA",
          fontNickname: ["35px", "25px"],
          fullname: "Akhtar Randrasyah",
          Divisi: "LASKAR",
          fontDivisi: ["35px", "25px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "AMADIO",
          fontNickname: ["32px", "23px"],
          fullname: "Amadio Juno",
          Divisi: "LASKAR",
          fontDivisi: ["35px", "25px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "JONATHAN",
          fontNickname: ["27px", "19px"],
          fullname: "Jonathan Immanuel",
          Divisi: "LASKAR",
          fontDivisi: ["35px", "25px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
        {
          link: "#",
          nickname: "ABHIRAMA",
          fontNickname: ["26px", "18px"],
          fullname: "Pria Abhirama Dewa",
          Divisi: "LASKAR",
          fontDivisi: ["35px", "25px"],
          image: "/team/tes.png",
          image2: "/team/tes2.png",
        },
      ],
    },
  ];
  
  export default ourTeam;
  