name: Build Docker images
 
on:
  push:
    branches: ["master"]
 
jobs:
  build-and-push-dockerfile-image:
    runs-on: ubuntu-latest
    environment: build-docker-image4
    env:  # 👈 define your variable here
      IMAGE_NAME: registry.dokploy.nimby.fun/csui24-web-dokploy
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.dokploy.nimby.fun
          username: ${{ secrets.REGISTRY_DOKPLOY_USER }}
          password: ${{ secrets.REGISTRY_DOKPLOY_PASS }}

      # create a unique tag for each build for debugging
      - name: Set Docker tag
        id: date
        run: echo "DATE_STAMP=$(date +%s)" > "$GITHUB_ENV"

      - name: Build and push Docker images
        uses: iloveitaly/github-action-nixpacks@main
        env:
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DOKPLOY_APPLICATION_ID: ${{ secrets.DOKPLOY_APPLICATION_ID }}
          DOKPLOY_AUTH_TOKEN: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
          DOKPLOY_URL: ${{ secrets.DOKPLOY_URL }}
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          NEXT_PUBLIC_ENABLED_REACTIONS: ${{ secrets.NEXT_PUBLIC_ENABLED_REACTIONS }}
          PRODUCTION: ${{ secrets.PRODUCTION }}
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:custom-${{ env.DATE_STAMP }}
            ${{ env.IMAGE_NAME }}:latest
            envs: |
              ADMIN_PASSWORD
              DATABASE_URL
              DOKPLOY_APPLICATION_ID
              DOKPLOY_AUTH_TOKEN
              DOKPLOY_URL
              NEXT_PUBLIC_BASE_URL
              NEXT_PUBLIC_ENABLED_REACTIONS
              PRODUCTION
      
      - name: Trigger Dokploy Deployment
        run: |
            curl -X 'POST' \
            'https://dokploy.nimby.fun/api/trpc/application.deploy' \
            -H 'accept: application/json' \
            -H 'x-api-key: ${{secrets.DOKPLOY_AUTH_TOKEN}}' \
            -H 'Content-Type: application/json' \
            -d '{
                "json":{
                    "applicationId": "${{ secrets.DOKPLOY_APPLICATION_ID }}"
                }
            }'
